version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    platform: linux/arm64
    build: ./backend
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/flask_db

  frontend:
    platform: linux/arm64
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
